version: "3.9"

services:
  main:
    build:
      context: .
      dockerfile: litefs.Dockerfile
    environment:
      - APP_NAME="main"
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
